### ISSUE TITLE
Add restaurant issue

### ISSUE THREAD

**Issue by WarHatch** [PauliusGrigaliunas/cafe-demo#32]
Add restaurant formoj į vieną iš eilučių įvedus ' simbolį išmetą error'a
![image](https://user-images.githubusercontent.com/20258194/30922332-79878eb4-a3b1-11e7-8c8f-15baf50ef1cd.png)

**Comment by Moduxx** [comment]
nenori pabandyt sutvarkyt? tu ten bandei su tuo generator
